Do not display duplicate reactions
ajbura/cinny pull request #1713
Opened 2024-04-28 18:44 UTC by TTTaevas

### Description

"Duplicate reactions" in this context means **reactions using the same key from the same user**

As there are two places in the code from where reactions can be gotten (`Reactions.tsx` & `ReactionViewer.tsx`), the code to fix the problem also appears twice
This code ignores (disables for a line) the `no-param-reassign` ESLint rule, as I couldn't find a way to return something of type `[string, Set<MatrixEvent>]` without returning the parameter itself

I must admit I don't really know if that's the right way to go about it

Fixes #1653

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2024-04-28 18:48 UTC, TTTaevas commented
I have read the CLA Document and I hereby sign the CLA

2024-10-20 03:31 UTC, Vishal-Merugu commented on src/app/organisms/room/message/Reactions.tsx
> +            events.findIndex((e) => e.sender?.userId === event.sender?.userId) === index
dont use findIndex inside filter use create a map instead to check the existence already

2024-10-20 03:32 UTC, Vishal-Merugu commented on src/app/organisms/room/reaction-viewer/ReactionViewer.tsx
> +            events.findIndex((e) => e.sender?.userId === event.sender?.userId) === index
same her

2024-10-20 03:32 UTC, Vishal-Merugu requested changes
Resolve the comments

2024-10-27 20:01 UTC, TTTaevas commented
Can't be bothered to solve conflicting files for a 6-month-old PR that was ignored, feel free to use parts of my code to make your own PR @Vishal-Merugu

2024-10-27 20:01 UTC, closed without merging