Add setting to enable 24-hour time format
ajbura/cinny pull request #1739
Opened 2024-05-14 15:04 UTC by agmm

### Description

Support for the 24-hour time format has been a frequently requested feature in the Cinny Matrix room and has been mentioned in at least one issue #60. This PR adds a toggle in the settings page that allows the user to switch between 12-hour and 24-hour time formats.

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2024-05-15 15:04 UTC, ajbura reviewed
changes look good. for the simplicity i think we should just call it as hour24Clock

2024-05-16 04:03 UTC, ajbura requested changes

2024-05-16 04:03 UTC, ajbura commented on src/app/components/message/Time.tsx
> +  const [hour24Clock] = useSetting(settingsAtom, 'hour24Clock');
Subscribing to `settingsAtom` inside `Time` component can downgrade the perf of our timeline as every `Time` component in every message will be listening to it where more perf oriented approach can be to receive `hour24Clock` as component param and we can subscribe to `settingsAtom` once for all.

2024-10-08 13:49 UTC, LevitatingBusinessMan commented
@agmm are you still willing to update this PR?

2024-10-08 16:48 UTC, agmm commented
I totally forgot about this PR, but yes, I am willing to update it. I will take a look as soon as I have the time.

2025-02-25 08:28 UTC, ajbura commented
Closing due to inactivity

2025-02-25 08:28 UTC, closed without merging