Load the local hostname's config, where possible
ajbura/cinny pull request #2071
Opened 2024-11-30 00:39 UTC by nexy7574

### Description
This change mirrors some nice but niche behaviour from Element, wherein `config.$HOSTNAME.json` is tried before `config.json`.
This is very handy, at least for me, because I serve cinny from a multitude of domains, but all from the same dist directory. This means if you visit cinny from one of my domains that is for a different homeserver, you will get the config for only one of my homeservers.
An example of this is https://cinny.transgender.ing - the `config.json` is loaded, which is intended for https://cinny.nexy7574.co.uk. Element, however, nicely tries to load `config.transgender.ing.json` in the first case, meaning I can serve a different default login server.

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

2024-11-30 00:42 UTC, nexy7574 commented on src/app/components/ClientConfigLoader.tsx
> +  if(config.status===404) {
It's worth noting that in the dev environment, `npm start` stupidly returns a `200` for this non-existent file. This isn't something that would happen in a production environment (I'd certainly hope at least!), but it does cause the dev server to throw an error while loading.

Might it be worth reading the JSON before returning it (or trying to) to see if the returned config is ACTUALLY 200 OK?

2024-12-03 12:57 UTC, nexy7574 commented on src/app/components/ClientConfigLoader.tsx
> +  if(config.status===404) {
it doesn't look like Element does this, so if I'm sticking to the original goal of basically just mirroring their behaviour, then this is sufficient.

2025-01-06 04:50 UTC, ajbura requested changes

2025-01-06 04:50 UTC, ajbura commented on src/app/components/ClientConfigLoader.tsx
> +  }
Getting config blocks the app from loading, so fetching multiple config in series increase the time to interactivity significantly. Please load the standard `base_url/config.json` first or fetch both of them in parallel.

2025-01-06 04:50 UTC, ajbura commented on src/app/components/ClientConfigLoader.tsx
> +  }
Please do not catch (and suppress) the error here as UI is responsible for caching and displaying them to user.

2025-02-16 04:27 UTC, closed without merging

2025-02-16 04:27 UTC, ajbura commented
Closing it. I feel like it is really complicating the error handling when loading config.