Fix not able to edit large room names and added limit to room's name upto 50
ajbura/cinny pull request #2104
Opened 2024-12-21 10:26 UTC by Vishawdeep-Singh

### Description

Fixes #2092 

**Before:** 

https://github.com/user-attachments/assets/6cd51dff-af9c-4415-bca3-9f8f160bbef1

**After my changes :** 

https://github.com/user-attachments/assets/2c06ff78-c79c-448a-b449-4a5a4b890dfd

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2024-12-21 10:28 UTC, Vishawdeep-Singh commented
I have read the CLA Document and I hereby sign the CLA

2024-12-29 04:16 UTC, Vishawdeep-Singh commented
@ajbura Can you also review this please ?

2025-01-06 04:36 UTC, ajbura requested changes
Hey, preventing user from entering room name above 50 char is a no go, the attached issue can be fixed with css styles only.

2025-01-06 05:32 UTC, Vishawdeep-Singh commented
> Hey, preventing user from entering room name above 50 char is a no go, the attached issue can be fixed with css styles only.

@ajbura  Hey,I want your opinion on this . Should i make room name Y-axis scrollable and keep edit option first OR just simply truncate the text.

2025-01-06 05:35 UTC, ajbura commented
word break will put the text in next line and keep the edit button visible

2025-01-06 06:12 UTC, Vishawdeep-Singh commented
> word break will put the text in next line and keep the edit button visible

@ajbura  Done

2025-02-16 04:13 UTC, ajbura requested changes

2025-02-16 04:13 UTC, ajbura commented on src/app/molecules/room-profile/RoomProfile.jsx
> +          overflowWrap: 'break-word',
This css is not required as the problem is in nested text.

2025-02-16 04:13 UTC, ajbura commented on src/app/molecules/room-profile/RoomProfile.jsx
> +            wordBreak: 'break-word',
`width` and `whiteSpace` are not really required for break word.

2025-02-16 04:13 UTC, ajbura commented on src/app/molecules/room-profile/RoomProfile.jsx
> +            style={{ marginTop: '8px' }}
not sure why this is added.

2025-03-22 03:39 UTC, ajbura commented
closing as fixed already

2025-03-22 03:39 UTC, closed without merging