Bug Fix - Tab Crashes when page limit exceeds a certain amout (e.g. 10000) on explore community tab.
ajbura/cinny pull request #2109
Opened 2024-12-22 08:27 UTC by Rajnish2105

### Description

Fixes #2072 

Before Changes:
https://github.com/user-attachments/assets/cc3674ad-18d6-40a2-9225-19569765daea

After Changes:
https://github.com/user-attachments/assets/1761a3b7-eb62-47a5-a766-e06dc2945887

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2024-12-22 08:28 UTC, Rajnish2105 commented
I have read the CLA Document and I hereby sign the CLA

2025-01-06 04:30 UTC, ajbura requested changes
Hey! I think adding a dialog for it is not really a good idea and instead we can set the input `max` to something around `1152` for blocking user from entering high range where application might break.

2025-02-16 04:03 UTC, ajbura requested changes

2025-02-16 04:03 UTC, ajbura commented on src/app/pages/client/explore/Server.tsx
> +                    }}
please remove the `onChange` as it is not required after adding `max` and also will break the input from changing value.

2025-02-16 04:03 UTC, ajbura commented on src/app/pages/client/explore/Server.tsx
> +                  </Chip>
It won't be a good idea to show this option considering that the performance will be poor.

2025-02-16 04:03 UTC, ajbura commented on src/app/pages/client/explore/Server.tsx
> +                    placeholder="Max limit- 10000"
that placeholder is misleading and not required as input already has a label

2025-02-16 04:03 UTC, ajbura commented on src/app/pages/client/explore/Server.tsx
> +// import { LimitWarning } from './LimitWarning';
please remove the commented code

2025-02-16 04:03 UTC, ajbura commented on src/app/pages/client/explore/Server.tsx
> +    // my work here
here as well

2025-03-22 03:39 UTC, ajbura commented
closing as no response.

2025-03-22 03:39 UTC, closed without merging